apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promscope.fullname" . }}
  labels:
    {{- include "promscope.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "promscope.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promscope.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: promscope
          image: {{ include "promscope.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: PROMSCOPE_LISTEN_ADDR
              value: {{ printf ":%v" .Values.port | quote }}
            - name: PROMSCOPE_PROMETHEUS_URL
              value: {{ required "prometheusURL is required" .Values.prometheusURL | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: http
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
